<Project>
  <PropertyGroup>
    <ContaPreArtifactsRoot Condition="'$(ContaPreArtifactsRoot)' == ''">$(MSBuildThisFileDirectory)artifacts</ContaPreArtifactsRoot>
    <BaseIntermediateOutputPath>$(ContaPreArtifactsRoot)\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
